Repository team-MUMENT/MUMENT-iOS, pull requests merged in 2022-11, with the labels that each got.

#152 [FEAT] 로그인 뷰
  MUMENT/MUMENT/Global/Extensions/UILabel+.swift
  MUMENT/MUMENT/Resources/Assets.xcassets/SignIn/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/SignIn/appleLogin.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/SignIn/appleLogin.imageset/appleLogin.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SignIn/appleLogin.imageset/appleLogin@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SignIn/appleLogin.imageset/appleLogin@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SignIn/kakaoLogin.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/SignIn/kakaoLogin.imageset/kakaoLogin.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SignIn/kakaoLogin.imageset/kakaoLogin@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SignIn/kakaoLogin.imageset/kakaoLogin@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SignIn/mumentLogoLogin.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/SignIn/mumentLogoLogin.imageset/mumentLogoLogin.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SignIn/mumentLogoLogin.imageset/mumentLogoLogin@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SignIn/mumentLogoLogin.imageset/mumentLogoLogin@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SignIn/signInBackground.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/SignIn/signInBackground.imageset/signInBackground.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SignIn/signInBackground.imageset/signInBackground@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SignIn/signInBackground.imageset/signInBackground@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/signInBackground.png
  MUMENT/MUMENT/Resources/Assets.xcassets/signInBackground@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/signInBackground@3x.png
  MUMENT/MUMENT/Sources/Scenes/SignIn/SignInVC.swift
Labels: 📱 UI

#155 [CHORE] 컬러, 폰트 업데이트
  MUMENT/MUMENT/Global/Extensions/UIColor+.swift
  MUMENT/MUMENT/Global/Extensions/UIFont+.swift
  MUMENT/MUMENT/Resources/Colorsets.xcassets/mRed.colorset/Contents.json
Labels: ✅ chore

#153 [CHORE] 기록하기 UI 수정
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentDelete2.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentDelete2.imageset/mumentDelete2.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentDelete2.imageset/mumentDelete2@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentDelete2.imageset/mumentDelete2@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentDelete3.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentDelete3.imageset/mumentDelete3.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentDelete3.imageset/mumentDelete3@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentDelete3.imageset/mumentDelete3@3x.png
  MUMENT/MUMENT/Sources/Components/DefaultNavigationBar.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentDetail/MumentDetailVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentHistory/MumentHistoryVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/SongDetailVC.swift
  MUMENT/MUMENT/Sources/Scenes/Write/LeftAlignedCollectionViewFlowLayout.swift
  MUMENT/MUMENT/Sources/Scenes/Write/WriteMusicView.swift
  MUMENT/MUMENT/Sources/Scenes/Write/WriteVC.swift
Labels: 📱 UI, ✅ chore

#159 [FEAT] 빨간색 토스트 메시지 구현
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Global/Extensions/UIViewController+.swift
  MUMENT/MUMENT/Global/Type/ToastMessageColorType.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/StorageBottomSheet.swift
  MUMENT/MUMENT/Sources/Scenes/Write/WriteVC.swift
Labels: 📱 UI

#151 [FEAT] 스플래시 구현
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Application/AppDelegate.swift
  MUMENT/MUMENT/Application/SceneDelegate.swift
  MUMENT/MUMENT/Resources/Assets.xcassets/mumentIcon.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/mumentIcon.imageset/mumentIcon.png
  MUMENT/MUMENT/Resources/Assets.xcassets/mumentIcon.imageset/mumentIcon@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/mumentIcon.imageset/mumentIcon@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/splashBackground.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/splashBackground.imageset/splashBackground.png
  MUMENT/MUMENT/Resources/Assets.xcassets/splashBackground.imageset/splashBackground@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/splashBackground.imageset/splashBackground@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/splashBackground.png
  MUMENT/MUMENT/Resources/Assets.xcassets/splashBackground@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/splashBackground@3x.png
  MUMENT/MUMENT/Sources/Scenes/Base.lproj/LaunchScreen.storyboard
  MUMENT/MUMENT/Sources/Scenes/SignIn/AutoSignInVC.swift
  MUMENT/MUMENT/Sources/Scenes/Splash/Splash.storyboard
Labels: 📱 UI

#160 [FEAT] 카카오, 애플 로그인
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Application/AppDelegate.swift
  MUMENT/MUMENT/Application/SceneDelegate.swift
  MUMENT/MUMENT/Info.plist
  MUMENT/MUMENT/MUMENT.entitlements
  MUMENT/MUMENT/Sources/Scenes/SignIn/SignInVC.swift
Labels: 📱 UI
