Repository team-MUMENT/MUMENT-iOS, pull requests merged in 2022-07, with the labels that each got.

#4 [CHORE] Font-Setting
  .gitignore
  MUMENT/MUMENT.xcodeproj/project.xcworkspace/xcuserdata/madilyn.xcuserdatad/UserInterfaceState.xcuserstate
  MUMENT/MUMENT/Global/Extensions/UIFont+.swift
Labels: ✅ chore

#6 [CHORE] TabBar 디자인 적용
  MUMENT/.DS_Store
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT.xcodeproj/project.xcworkspace/xcuserdata/madilyn.xcuserdatad/UserInterfaceState.xcuserstate
  MUMENT/MUMENT/.DS_Store
  MUMENT/MUMENT/Global/Extensions/CALayer+.swift
  MUMENT/MUMENT/Global/Extensions/UIColor+.swift
  MUMENT/MUMENT/Sources/MumentTabBarController.swift
Labels: 📱 UI, ✅ chore

#9 [CHORE] Font 스펙 수정
  MUMENT/MUMENT/Global/Extensions/UIFont+.swift
Labels: ✅ chore

#10 [FEAT] DefaultNavigationView 구현
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Global/Extensions/Adjusted+.swift
  MUMENT/MUMENT/Global/Extensions/CALayer+.swift
  MUMENT/MUMENT/Global/Extensions/UILabel+.swift
  MUMENT/MUMENT/Sources/Components/DefaultNavigationView.swift
  MUMENT/MUMENT/Sources/Components/d.swift
  MUMENT/MUMENT/Sources/MumentTabBarController.swift
  MUMENT/MUMENT/Sources/Scenes/Write/WriteVC.swift
Labels: 📱 UI

#29 [FEAT] 완료 버튼 컴포넌트 구현
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Sources/Components/MumentCompleteButton.swift
Labels: 📱 UI

#26 [FEAT] 홈 뷰 상단 바 구현
  MUMENT/.DS_Store
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Global/Extensions/UIFont+.swift
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentLogo.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentLogo.imageset/mumentLogo.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentLogo.imageset/mumentLogo@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentLogo.imageset/mumentLogo@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentMusicnote.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentMusicnote.imageset/mumentMusicnote.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentMusicnote.imageset/mumentMusicnote@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentMusicnote.imageset/mumentMusicnote@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentNoti.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentNoti.imageset/mumentNoti.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentNoti.imageset/mumentNoti@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentNoti.imageset/mumentNoti@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentSearch.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentSearch.imageset/mumentSearch.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentSearch.imageset/mumentSearch@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentSearch.imageset/mumentSearch@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentSearchbar.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentSearchbar.imageset/mumentSearchbar.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentSearchbar.imageset/mumentSearchbar@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/mumentSearchbar.imageset/mumentSearchbar@3x.png
  MUMENT/MUMENT/Sources/Scenes/Home/CarouselTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/HomeTVHeader.swift
  MUMENT/MUMENT/Sources/Scenes/Home/HomeVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentForTodayTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentsByTagTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/RecentMumentsTVC.swift
Labels: 📱 UI

#32 [CHORE] README 작성
  README.md
Labels: ✅ chore

#36 [FEAT] 홈 배너 구현
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Global/Extensions/UITableViewCell+.swift
  MUMENT/MUMENT/Global/Extensions/UIView+.swift
  MUMENT/MUMENT/Global/Extensions/UIViewController+.swift
  MUMENT/MUMENT/Resources/Assets.xcassets/Home Dummy Data/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/Home Dummy Data/home_banner1.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/Home Dummy Data/home_banner1.imageset/Rectangle 4525.png
  MUMENT/MUMENT/Resources/Assets.xcassets/Home Dummy Data/image1.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/Home Dummy Data/image1.imageset/image1.svg
  MUMENT/MUMENT/Resources/Assets.xcassets/Home Dummy Data/image2.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/Home Dummy Data/image2.imageset/image2.svg
  MUMENT/MUMENT/Resources/Assets.xcassets/Home Dummy Data/image3.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/Home Dummy Data/image3.imageset/image3.svg
  MUMENT/MUMENT/Sources/Scenes/Home/CarouselCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/CarouselTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/HomeVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/CarouselModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/ma.swift
Labels: 📱 UI

#41 [DOCS] 과제 README 작성
  README.md
Labels: 📔 docs

#40 [FEAT] '오늘의 뮤멘트' 섹션 구현
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Resources/Assets.xcassets/Home Dummy Data/image4.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/Home Dummy Data/image4.imageset/rectangle573.png
  MUMENT/MUMENT/Resources/Assets.xcassets/Home Dummy Data/image4.imageset/rectangle573@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/Home Dummy Data/image4.imageset/rectangle573@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/heart.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/heart.imageset/heart.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/heart.imageset/heart@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/heart.imageset/heart@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/heart_filled.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/HomeIcons/heart_filled.imageset/heart_filled.svg
  MUMENT/MUMENT/Sources/Components/DefaultMumentCard/DefaultMumentCardModel.swift
  MUMENT/MUMENT/Sources/Components/DefaultMumentCard/DefaultMumentCardView.swift
  MUMENT/MUMENT/Sources/Components/DefaultTagView.swift
  MUMENT/MUMENT/Sources/Components/MumentCardWithoutHeart/MumentCardWithoutHeartModel.swift
  MUMENT/MUMENT/Sources/Components/MumentCardWithoutHeart/MumentCardWithoutHeartView.swift
  MUMENT/MUMENT/Sources/Scenes/Home/CarouselCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/HomeVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentForTodayTVC.swift
Labels: 📱 UI

#45 [FEAT] 태그별 뮤멘트 추천 섹션 구현
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Sources/Scenes/Home/HomeTVHeader.swift
  MUMENT/MUMENT/Sources/Scenes/Home/HomeVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/MumentsByTagModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/MumentsByTagTitleModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentsByTagCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentsByTagTVC.swift
Labels: 📱 UI

#46 [FEAT] 기록하기 뷰 UI 디테일
  MUMENT/MUMENT/Sources/Scenes/Write/WriteVC.swift
Labels: 📱 UI

#55 [FEAT] 뷰 전환 버튼 클릭에 따른 컬렉션 뷰 셀 전환 구현
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Sources/Scenes/Home/Main/HomeVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/AlbumCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/CellCategory.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/LikedMumentVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/ListCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/MyMumentVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/StorageVC.swift
Labels: 📱 UI

#60 [FEAT] Storage탭 뮤멘트 카드 shadow, 리스트, 앨범 뷰 전환 작업
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Sources/Scenes/Storage/AlbumCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/CellCategory.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/LikedMumentVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/ListCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/MyMumentVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/SectionHeader.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/StorageVC.swift
Labels: 📱 UI

#58 [FEAT] 검색 뷰 구현
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Global/Extensions/UIImageView+.swift
  MUMENT/MUMENT/Network/ImageCacheManager.swift
  MUMENT/MUMENT/Resources/Assets.xcassets/SearchIcons/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/SearchIcons/mumentAlertIcn.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/SearchIcons/mumentAlertIcn.imageset/mumentAlertIcn.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SearchIcons/mumentAlertIcn.imageset/mumentAlertIcn@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SearchIcons/mumentAlertIcn.imageset/mumentAlertIcn@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SearchIcons/mumentDelete.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/SearchIcons/mumentDelete.imageset/mumentDelete.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SearchIcons/mumentDelete.imageset/mumentDelete@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SearchIcons/mumentDelete.imageset/mumentDelete@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SearchIcons/mumentIconBack.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/SearchIcons/mumentIconBack.imageset/mumentIconBack.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SearchIcons/mumentIconBack.imageset/mumentIconBack@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SearchIcons/mumentIconBack.imageset/mumentIconBack@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SearchIcons/recentSearchEmpty.imageset/01.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SearchIcons/recentSearchEmpty.imageset/01@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SearchIcons/recentSearchEmpty.imageset/01@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/SearchIcons/recentSearchEmpty.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentReset.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentReset.imageset/mumentReset.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentReset.imageset/mumentReset@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentReset.imageset/mumentReset@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentToggleOff.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentToggleOff.imageset/mumentToggleOff.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentToggleOff.imageset/mumentToggleOff@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentToggleOff.imageset/mumentToggleOff@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentToggleOn.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentToggleOn.imageset/mumentToggleOn.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentToggleOn.imageset/mumentToggleOn@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentToggleOn.imageset/mumentToggleOn@3x.png
  MUMENT/MUMENT/Sources/Scenes/Search/EmptyView/RecentSearchEmptyView.swift
  MUMENT/MUMENT/Sources/Scenes/Search/EmptyView/SearchResultEmptyView.swift
  MUMENT/MUMENT/Sources/Scenes/Search/Models/MusicForSearchModel.swift
  MUMENT/MUMENT/Sources/Scenes/Search/RecentSearchTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Search/SearchTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Search/SearchTVType.swift
  MUMENT/MUMENT/Sources/Scenes/Search/SearchVC.swift
Labels: 📱 UI

#64 [FEAT] 확인, 취소 Alert 재사용 컴포넌트 구현 [FEAT] 검색-모두삭제 Alert 적용
  MUMENT/MUMENT/Sources/Components/MumentAlertWithButtons/MumentAlertWithButtons.swift
  MUMENT/MUMENT/Sources/Scenes/Search/SearchVC.swift
Labels: 📱 UI

#71 [FEAT] 검색 bottom sheet UI 구현
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Global/Extensions/Notification+Name+.swift
  MUMENT/MUMENT/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentDelete2.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentDelete2.imageset/mumentDelete2.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentDelete2.imageset/mumentDelete2@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentDelete2.imageset/mumentDelete2@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentHeadSetEmptyRecentSearch.imageset/02.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentHeadSetEmptyRecentSearch.imageset/02@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentHeadSetEmptyRecentSearch.imageset/02@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/WriteIcons/mumentHeadSetEmptyRecentSearch.imageset/Contents.json
  MUMENT/MUMENT/Sources/Scenes/Search/EmptyView/RecentSearchEmptyView.swift
  MUMENT/MUMENT/Sources/Scenes/Write/SearchBottomSheetVC.swift
  MUMENT/MUMENT/Sources/Scenes/Write/SearchForWriteView.swift
  MUMENT/MUMENT/Sources/Scenes/Write/WriteMusicView.swift
  MUMENT/MUMENT/Sources/Scenes/Write/WriteVC.swift
Labels: 📱 UI

#73 [FEAT] 스크롤 고정 영역 점검 및 수정
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Resources/Assets.xcassets/Home Dummy Data/history_btn.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/Home Dummy Data/history_btn.imageset/history_btn.png
  MUMENT/MUMENT/Resources/Assets.xcassets/Home Dummy Data/history_btn.imageset/history_btn@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/Home Dummy Data/history_btn.imageset/history_btn@3x.png
  MUMENT/MUMENT/Sources/Scenes/Home/Main/HomeTVHeader.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/HomeVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentDetail/MumentDetailVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/SongDetailVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/SongInfoTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Search/SearchVC.swift
Labels: 📱 UI

#74 [CHORE] 네트워크 세팅
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Network/APIEssentials/APIConstants.swift
  MUMENT/MUMENT/Network/APIEssentials/GenericResponse.swift
  MUMENT/MUMENT/Network/APIEssentials/NetworkConstants.swift
  MUMENT/MUMENT/Network/APIManagers/BaseAPI.swift
  MUMENT/MUMENT/Network/APIManagers/SignAPI.swift
  MUMENT/MUMENT/Network/Bases/NetworkResult.swift
  MUMENT/MUMENT/Network/Bases/TargetType.swift
  MUMENT/MUMENT/Network/EventLogger.swift
  MUMENT/MUMENT/Network/Services/SignService.swift
  MUMENT/MUMENT/Network/Services/zzService.swift
  MUMENT/MUMENT/Sources/Scenes/SignIn/Model/SignInBodyModel.swift
  MUMENT/MUMENT/Sources/Scenes/SignIn/Model/SignInDataModel.swift
  MUMENT/MUMENT/Sources/Scenes/SignIn/SignInVC.swift
Labels: ✅ chore

#78 [FEAT] 뮤멘트 카드들 태그 부분 구현
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Global/Extensions/UIStackView+.swift
  MUMENT/MUMENT/Sources/Components/DefaultMumentCard/DefaultMumentCardModel.swift
  MUMENT/MUMENT/Sources/Components/DefaultMumentCard/DefaultMumentCardView.swift
  MUMENT/MUMENT/Sources/Components/DefaultTagView.swift
  MUMENT/MUMENT/Sources/Components/DetailMumentCard/DetailMumentCardView.swift
  MUMENT/MUMENT/Sources/Components/MumentCardBySongView.swift
  MUMENT/MUMENT/Sources/Components/MumentCardWithoutHeart/MumentCardWithoutHeartModel.swift
  MUMENT/MUMENT/Sources/Components/MumentCardWithoutHeart/MumentCardWithoutHeartView.swift
  MUMENT/MUMENT/Sources/Components/TagView.swift
  MUMENT/MUMENT/Sources/Preview.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/HomeVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/MumentForTodayTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/MumentsByTagTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/MumentsOfRevisitedTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/MumentCardBySongModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/MumentDetailVCModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentDetail/MumentDetailVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentHistory/MumentHistoryVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/SongDetailVC.swift
Labels: 📱 UI

#79 [FEAT] StorageVC EmptyView 구현
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/likedMumentEmptyImage.imageset/03.png
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/likedMumentEmptyImage.imageset/03@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/likedMumentEmptyImage.imageset/03@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/likedMumentEmptyImage.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/recordBtn2.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/recordBtn2.imageset/recordBtn2.png
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/recordBtn2.imageset/recordBtn2@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/recordBtn2.imageset/recordBtn2@3x.png
  MUMENT/MUMENT/Sources/Scenes/Storage/StorageEmptyView.swift
Labels: 📱 UI

#81 [FEAT] 뮤멘트 상세보기 팝업 창 구현
  MUMENT/MUMENT/Sources/Components/DetailMumentCard/DetailMumentCardView.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentDetail/MumentDetailVC.swift
Labels: 📱 UI

#92 [FEAT] 뮤멘트 상세보기 뷰 API 연결
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Global/Extensions/UIStackView+.swift
  MUMENT/MUMENT/Network/APIManagers/HistoryAPI.swift
  MUMENT/MUMENT/Network/APIManagers/HomeAPI.swift
  MUMENT/MUMENT/Network/APIManagers/MumentDetailAPI.swift
  MUMENT/MUMENT/Network/APIManagers/SongDetailAPI.swift
  MUMENT/MUMENT/Network/Services/MumentDetailService.swift
  MUMENT/MUMENT/Network/Services/SongDetailService.swift
  MUMENT/MUMENT/Sources/Components/DetailMumentCard/DetailMumentCardView.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/AllMumentsResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/MumentDetailResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentDetail/DetailSongInfoView.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentDetail/MumentDetailVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/SongDetailVC.swift
Labels: 📡 network

#95 [Feat] 바텀시트 UI 및 적용 로직 구현
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Global/Extensions/NSObject+.swift
  MUMENT/MUMENT/Global/Extensions/UIButton+.swift
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/allDeselectedButton.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/allDeselectedButton.imageset/allDeselectedButton.png
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/allDeselectedButton.imageset/allDeselectedButton@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/allDeselectedButton.imageset/allDeselectedButton@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/mumentDelete.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/mumentDelete.imageset/mumentDelete.png
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/mumentDelete.imageset/mumentDelete@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/mumentDelete.imageset/mumentDelete@3x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/mumentTagDelete.imageset/Contents.json
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/mumentTagDelete.imageset/mumentTagDelete.png
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/mumentTagDelete.imageset/mumentTagDelete@2x.png
  MUMENT/MUMENT/Resources/Assets.xcassets/StorageIcons/mumentTagDelete.imageset/mumentTagDelete@3x.png
  MUMENT/MUMENT/Sources/Scenes/Storage/Model/TagButton.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/Model/ss.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/StorageBottomSheet.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/StorageVC.swift
Labels: 📱 UI

#94 [FEAT] 기록하기 뷰 API 연결
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Global/Extensions/String+.swift
  MUMENT/MUMENT/Global/Singleton/UserInfo.swift
  MUMENT/MUMENT/Network/APIManagers/SearchAPI.swift
  MUMENT/MUMENT/Network/APIManagers/SignAPI.swift
  MUMENT/MUMENT/Network/APIManagers/WriteAPI.swift
  MUMENT/MUMENT/Network/Services/SearchService.swift
  MUMENT/MUMENT/Network/Services/WriteService.swift
  MUMENT/MUMENT/Sources/MumentTabBarController.swift
  MUMENT/MUMENT/Sources/Scenes/Search/Models/SearchResultResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Search/SearchTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Search/SearchVC.swift
  MUMENT/MUMENT/Sources/Scenes/SignIn/Model/SignInDataModel.swift
  MUMENT/MUMENT/Sources/Scenes/SignIn/SignInVC.swift
  MUMENT/MUMENT/Sources/Scenes/Write/Model/GetIsFirstResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Write/Model/PostMumentBodyModel.swift
  MUMENT/MUMENT/Sources/Scenes/Write/Model/PostMumentResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Write/Model/ww.swift
  MUMENT/MUMENT/Sources/Scenes/Write/SearchForWriteView.swift
  MUMENT/MUMENT/Sources/Scenes/Write/WriteMusicView.swift
  MUMENT/MUMENT/Sources/Scenes/Write/WriteVC.swift
Labels: 📡 network

#98 [FEAT] 뮤멘트 히스토리 뷰 히스토리 API 연결
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Network/APIManagers/HistoryAPI.swift
  MUMENT/MUMENT/Network/Services/HistorySerivce.swift
  MUMENT/MUMENT/Sources/Components/MumentCardBySongTVC.swift
  MUMENT/MUMENT/Sources/Components/MumentCardBySongView.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/ResponseModel/HistoryResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/ResponseModel/MumentDetailResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentDetail/DetailSongInfoView.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentDetail/MumentDetailVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentHistory/MumentHistoryTVHeader.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentHistory/MumentHistoryVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/SongDetailVC.swift
Labels: 📡 network

#99 [FEAT] 곡 상세보기 뷰 곡 정보, 내가 기록한 뮤멘트 API 연결
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Network/APIManagers/SongDetailAPI.swift
  MUMENT/MUMENT/Network/Services/SongDetailService.swift
  MUMENT/MUMENT/Sources/Components/MumentCardBySongTVC.swift
  MUMENT/MUMENT/Sources/Components/MumentCardBySongView.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/ResponseModel/SongInfoResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/AllMumentsSectionHeader.swift
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/MyMumentSectionHeader.swift
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/SongDetailVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/SongInfoTVC.swift
Labels: 📡 network

#100 [FEAT] 최근 검색한 곡 기능 구현
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Global/Extensions/UIImageView+.swift
  MUMENT/MUMENT/Global/Extensions/UserDefaults+.swift
  MUMENT/MUMENT/Sources/Scenes/Search/Models/SearchResultResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Search/RecentSearchTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Search/SearchVC.swift
  MUMENT/MUMENT/Sources/Scenes/Write/SearchForWriteView.swift
Labels: 📡 network, 📱 UI

#101 [Fix] 바텀시트 UI 및 로직 이슈 해결
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Network/APIManagers/StorageAPI.swift
  MUMENT/MUMENT/Network/Services/StorageService.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/Model/GetMyMumentStorageResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/StorageBottomSheet.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/StorageVC.swift
Labels: 🐞 bug & fix, ✅ chore

#103 [FIX] 기록하기 UI 이슈 대응
  MUMENT/MUMENT/Sources/Scenes/Write/WriteVC.swift
Labels: 🐞 bug & fix, 📱 UI

#105 [Feat] 홈 뷰 API 연결
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Network/APIManagers/HomeAPI.swift
  MUMENT/MUMENT/Network/APIManagers/MumentDetailAPI.swift
  MUMENT/MUMENT/Network/Services/HomeService.swift
  MUMENT/MUMENT/Sources/Components/MumentCardWithoutHeart/MumentCardWithoutHeartView.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/CarouselCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/CarouselTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/HomeVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/MumentForTodayTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/MumentsByTagCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/MumentsByTagTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/MumentsOfRevisitedCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/MumentsOfRevisitedTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/ResponseModel/CarouselResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/ResponseModel/MumentForTodayResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/ResponseModel/MumentsByTagResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/ResponseModel/MumentsOfRevisitedResponseModel.swift
Labels: 📡 network, 📱 UI

#106 [FIX] 검색하기 UI 및 로직 이슈 수정
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/SongDetailVC.swift
  MUMENT/MUMENT/Sources/Scenes/Search/EmptyView/RecentSearchEmptyView.swift
  MUMENT/MUMENT/Sources/Scenes/Search/SearchVC.swift
  MUMENT/MUMENT/Sources/Scenes/Write/SearchForWriteView.swift
Labels: 📱 UI

#108 [FEAT] 홈 뷰 UI 수정
  MUMENT/MUMENT/Sources/Components/DefaultMumentCard/DefaultMumentCardView.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/CarouselCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/CarouselTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/HomeTVHeader.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/MumentForTodayTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/MumentsByTagTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/MumentsOfRevisitedTVC.swift
Labels: 📱 UI

#109 [Feat] 좋아요한 뮤멘트 API 연결
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Network/APIManagers/StorageAPI.swift
  MUMENT/MUMENT/Network/Services/StorageService.swift
  MUMENT/MUMENT/Sources/Components/MumentCardWithoutHeart/MumentCardWithoutHeartView.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/AlbumCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/LikedMumentVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/ListCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/Model/GetLikedMumentResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/Model/GetMyMumentResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/MyMumentVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/SectionHeader.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/StorageBottomSheet.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/StorageVC.swift
Labels: 🐞 bug & fix, 📡 network, ✅ chore

#114 [DOCS] 최종 과제 README 작성
  README.md
Labels: 📔 docs

#117 [FIX] 바텀시트 UI 레이아웃 수정
  MUMENT/MUMENT/Sources/Scenes/Storage/StorageBottomSheet.swift
Labels: 📱 UI

#118 [FEAT] QA 및 발견된 이슈 해결
  MUMENT/MUMENT/Sources/Components/MumentCardBySongView.swift
  MUMENT/MUMENT/Sources/Components/MumentCardWithoutHeart/MumentCardWithoutHeartView.swift
  MUMENT/MUMENT/Sources/Components/OrderingButton.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentDetail/DetailSongInfoView.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentHistory/MumentHistoryTVHeader.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentHistory/MumentHistoryVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/AllMumentsSectionHeader.swift
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/MyMumentSectionHeader.swift
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/SongDetailVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/SongInfoTVC.swift
Labels: 📱 UI

#119 Fix/#116 mument detail history data
  MUMENT/MUMENT/Sources/Components/DetailMumentCard/DetailMumentCardView.swift
  MUMENT/MUMENT/Sources/Components/MumentCardBySongView.swift
  MUMENT/MUMENT/Sources/Components/MumentCardWithoutHeart/MumentCardWithoutHeartView.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/CarouselCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/CarouselTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Main/MumentsOfRevisitedCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/ResponseModel/AllMumentsResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/ResponseModel/CarouselResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/ResponseModel/HistoryResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/ResponseModel/MumentDetailResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/ResponseModel/MumentForTodayResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/ResponseModel/MumentsOfRevisitedResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/ResponseModel/SongInfoResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentDetail/DetailSongInfoView.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentDetail/MumentDetailVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/SongInfoTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Search/Models/SearchResultResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Search/RecentSearchTVC.swift
  MUMENT/MUMENT/Sources/Scenes/Search/SearchTVC.swift
  MUMENT/MUMENT/Sources/Scenes/SignIn/Model/SignInDataModel.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/AlbumCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/Model/GetLikedMumentResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/Model/GetMyMumentResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Write/WriteMusicView.swift
Labels: 🐞 bug & fix

#120 [Feat] 좋아요한 뮤멘트 날짜별 셀 구분 로직 구현
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Global/Extensions/Sequence+.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/LikedMumentVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/StorageBottomSheet.swift
Labels: 📡 network

#122 Fix/#116 mument detail history data
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Sources/Components/DetailMumentCard/DetailMumentCardView.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/ResponseModel/MumentDetailResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentDetail/MumentDetailVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentHistory/MumentHistoryVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/SongDetailVC.swift
Labels: 🐞 bug & fix

#123 [Feat] 보관함 탭 나의 뮤멘트 API 연결 #121
  MUMENT/MUMENT/Sources/Components/DefaultMumentCard/DefaultMumentCardView.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/AlbumCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/LikedMumentVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/ListCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/MyMumentVC.swift
Labels: 📡 network

#125 Fix/#116 mument detail history data
  MUMENT/MUMENT/Sources/MumentTabBarController.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentHistory/MumentHistoryVC.swift
Labels: 🐞 bug & fix

#126 [FEAT] 좋아요, 좋아요 취소, 삭제하기 연결
  MUMENT/MUMENT.xcodeproj/project.pbxproj
  MUMENT/MUMENT/Network/APIManagers/DeleteAPI.swift
  MUMENT/MUMENT/Network/APIManagers/LikeAPI.swift
  MUMENT/MUMENT/Network/Services/DeleteService.swift
  MUMENT/MUMENT/Network/Services/LikeService.swift
  MUMENT/MUMENT/Sources/Components/DefaultMumentCard/DefaultMumentCardView.swift
  MUMENT/MUMENT/Sources/Components/DetailMumentCard/DetailMumentCardView.swift
  MUMENT/MUMENT/Sources/Components/MumentCardBySongTVC.swift
  MUMENT/MUMENT/Sources/Components/MumentCardBySongView.swift
  MUMENT/MUMENT/Sources/Components/MumentCardWithoutHeart/MumentCardWithoutHeartView.swift
  MUMENT/MUMENT/Sources/Scenes/Home/Model/ResponseModel/LikeResponseModel.swift
  MUMENT/MUMENT/Sources/Scenes/Home/MumentDetail/MumentDetailVC.swift
  MUMENT/MUMENT/Sources/Scenes/Home/SongDetail/SongDetailVC.swift
Labels: 📡 network, 📱 UI

#127 [Feat] 나의 보관함 뮤멘트 API 연결
  MUMENT/MUMENT/Sources/Scenes/Storage/LikedMumentVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/MyMumentVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/StorageVC.swift
Labels: 📡 network

#129 [FIX] 결과가 없는 태그 선택시 엠티뷰 연결
  MUMENT/MUMENT/Sources/Scenes/Storage/LikedMumentVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/ListCVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/MyMumentVC.swift
  MUMENT/MUMENT/Sources/Scenes/Storage/SectionHeader.swift
Labels: 🐞 bug & fix
